### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by McNose** [stephenhouser/PinballY-Wheel-Actions#1]
Hey Stephen,

I just want to let you know, that your work is really awesome.
Great job.
This is exactly what I have been looking for. The wheel actions are definetly missing in Pinbally.

I am a bit surprised, that I haven´t seen it earlier.
Your work seems to be a hidden gem.

I will advertise it.

Regards
McNose

**Comment by stephenhouser** [comment]
Thank you. Props to PinballY itself for making this possible!

I assume you have found the larger repo of modifications at https://github.com/PinballY/PinballY-Addons-and-Examples

**Comment by McNose** [comment]
Yes. I already found that repo. 
Thank you.
